# Generated by Django 3.2.7 on 2022-02-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='incom_date',
            field=models.DateField(auto_now=True),
        ),
    ]
